export * from "./admin";
export * from "./parent";
export * from "./student";
export * from "./subject";
export * from "./score";
export * from "./attendance";
export * from "./notification";
export * from "./feedback";
export * from "./auth";
